# Generated by Django 4.1.2 on 2022-12-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_viaje_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viaje',
            new_name='Destino',
        ),
    ]
