# Generated by Django 4.1.2 on 2022-12-02 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_destino_image_destino_owner_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destino',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
