# Generated by Django 4.1.2 on 2022-12-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_destino_created_at_destino_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
