# Generated by Django 4.1.2 on 2022-11-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_accommodation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
