# Generated by Django 4.1.2 on 2022-12-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_alter_accommodation_options_accommodation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='image',
        ),
    ]
